services:
  accounts:
    image: "sanish07/accounts-aerobank:v2"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aerobank
  loans:
    image: "sanish07/loans-aerobank:v2"
    container_name: loans-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aerobank
  cards:
    image: "sanish07/cards-aerobank:v2"
    container_name: cards-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aerobank
networks:
  aerobank:
    driver: "bridge"