spring:
  application:
      name: loans
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:loansdb
    username: sanish
    password: sanish
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active: "prod"

server:
  port: 8082

build:
  version: "3.0"

loans:
  message: "Welcome to Aerobank Loans REST API services"
  contactDetails:
    name: "Sanish - FS Developer"
    email : "sanishnirwan@gmail.com"
  onCallSupport:
    - (555) 784-4552
    - (555) 781-1651
