spring:
  application:
      name: loans
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:loansdb
    username: sanish
    password: sanish
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8084/"
  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
