build:
  version: "2.0"

accounts:
  message: "Welcome to Aerobank Accounts REST API Production services"
  contactDetails:
    name: "Martinez - Product Engineer"
    email : "martinez@gmail.com"
  onCallSupport:
    - (555) 986-0012
    - (555) 927-6271