build:
  version: "3.0"

cards:
  message: "Welcome to Aerobank Cards REST API services"
  contactDetails:
    name: "Sanish - FS Developer"
    email : "sanishnirwan@gmail.com"
  onCallSupport:
    - (555) 784-4552
    - (555) 781-1651
