build:
  version: "2.0"

loans:
  message: "Welcome to Aerobank Loans REST API Production services"
  contactDetails:
    name: "Emanuel Pope - Devops Lead"
    email : "popeeman.21@gmail.com"
  onCallSupport:
    - (555) 441-9633
    - (555) 419-1261