spring:
  application:
     name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3308/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always  #Always init the schema.sql file in classpath for creating the database schema
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8084/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081


