services:
  network-deploy-service:  #Common For all ms. extension in this file
    networks:
      - eazybank

  microservice-base-config: #For configserver only
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config: #To be extended by accounts, loans, cards
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
