spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
           search-locations: "classpath:/config"
           #search-locations: "file:///D://config" #Storing config in filesystem

server:
  port: 8084
